title: <p align="center"> Thariq Khalid </p>
logo: /assets/img/logo.jpeg

description:
  <p align="center"> 
  <a href = "https://www.linkedin.com/in/thariqkhalid-deeplearning/">LinkedIn</a>
  <a href = "https://github.com/thariqkhalid">GitHub</a>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
